### ISSUE TITLE
HelloHacktoberfest - GoLang

### ISSUE THREAD

**Issue by ajjayymahato** [ajjayymahato/HelloHacktoberfest#16]

**Comment by krittika2004** [comment]
@ajjayymahato Kindly assign this issue to me

**Comment by ajjayymahato** [comment]
@krittika2004 Done. Do check the other repo as well, ToDoApp. Also if you like then give stars to the repos.

**Comment by krittika2004** [comment]
> @krittika2004 Done. Do check the other repo as well, ToDoApp. Also if you like then give stars to the repos.

Thanks
